options:
  cloudinformation_backend_proto:
    default: http
    description: 'cloudinformation backend protocol [http|https]'
    type: string
  cloudinformation_location:
    default: /v1/
    description: cloudinformation path component
    type: string
  cloudinformation_overwrite:
    default: ''
    description: cloudinformation specific apache overwrite (Base64)
    type: string
  cloudinformation_port:
    default: 8000
    description: cloudinformation frontend port
    type: int
  cloudinformation_securityrules:
    default: ''
    description: cloudinformation specific security rules (Base64)
    type: string
  cloudinformation_ssl_cert:
    default: ''
    description: cloudinformation frontend SSL certificate (Base64)
    type: string
  cloudinformation_ssl_key:
    default: ''
    description: cloudinformation frontend SSL key (Base64)
    type: string
  compute_backend_proto:
    default: http
    description: 'compute backend protocol [http|https]'
    type: string
  compute_location:
    default: /v2/acb87b9319bc414db8d9ad5b0dbe1aa4/
    description: compute path component
    type: string
  compute_overwrite:
    default: ''
    description: compute specific apache overwrite (Base64)
    type: string
  compute_port:
    default: 8774
    description: compute frontend port
    type: int
  compute_securityrules:
    default: ''
    description: compute specific security rules
    type: string
  compute_ssl_cert:
    default: ''
    description: compute frontend SSL certificate (Base64)
    type: string
  compute_ssl_key:
    default: ''
    description: compute frontend SSL key (Base64)
    type: string
  identity_backend_proto:
    default: http
    description: 'identity backend protocol [http|https]'
    type: string
  identity_location:
    default: /v2.0/
    description: identity path component
    type: string
  identity_overwrite:
    default: ''
    description: identity specific apache overwrite (Base64)
    type: string
  identity_port:
    default: 5000
    description: identity frontend port
    type: int
  identity_securityrules:
    default: ''
    description: identity specific security rules
    type: string
  identity_ssl_cert:
    default: ''
    description: identity frontend SSL certificate (Base64)
    type: string
  identity_ssl_key:
    default: ''
    description: identity frontend SSL key (Base64)
    type: string
  image_backend_proto:
    default: http
    description: 'image backend protocol [http|https]'
    type: string
  image_location:
    default: /
    description: image path component
    type: string
  image_overwrite:
    default: ''
    description: image specific apache overwrite (Base64)
    type: string
  image_port:
    default: 9292
    description: image frontend port
    type: int
  image_securityrules:
    default: ''
    description: image specific security rules
    type: string
  image_ssl_cert:
    default: ''
    description: image frontend SSL certificate (Base64)
    type: string
  image_ssl_key:
    default: ''
    description: image frontend SSL key (Base64)
    type: string
  metering_backend_proto:
    default: http
    description: 'metering backend protocol [http|https]'
    type: string
  metering_location:
    default: /
    description: metering path component
    type: string
  metering_overwrite:
    default: ''
    description: metering specific apache overwrite (Base64)
    type: string
  metering_port:
    default: 8777
    description: metering frontend port
    type: int
  metering_securityrules:
    default: ''
    description: metering specific security rules
    type: string
  metering_ssl_cert:
    default: ''
    description: metering frontend SSL certificate (Base64)
    type: string
  metering_ssl_key:
    default: ''
    description: metering frontend SSL key (Base64)
    type: string
  network_backend_proto:
    default: http
    description: 'network backend protocol [http|https]'
    type: string
  network_location:
    default: /
    description: network path component
    type: string
  network_overwrite:
    default: ''
    description: network specific apache overwrite (Base64)
    type: string
  network_port:
    default: 9696
    description: network frontend port
    type: int
  network_securityrules:
    default: ''
    description: network specific security rules
    type: string
  network_ssl_cert:
    default: ''
    description: network frontend SSL certificate (Base64)
    type: string
  network_ssl_key:
    default: ''
    description: network frontend SSL key (Base64)
    type: string
  objectstorage_backend_proto:
    default: http
    description: 'objectstorage backend protocol [http|https]'
    type: string
  objectstorage_location:
    default: /
    description: objectstorage path component
    type: string
  objectstorage_overwrite:
    default: ''
    description: objectstorage specific apache overwrite (Base64)
    type: string
  objectstorage_port:
    default: 443
    description: objectstorage frontend port
    type: int
  objectstorage_securityrules:
    default: ''
    description: objectstorage specific security rules
    type: string
  objectstorage_ssl_cert:
    default: ''
    description: objectstorage frontend SSL certificate (Base64)
    type: string
  objectstorage_ssl_key:
    default: ''
    description: objectstorage frontend SSL key (Base64)
    type: string
  orchestration_backend_proto:
    default: http
    description: 'orchestration backend protocol [http|https]'
    type: string
  orchestration_location:
    default: /v1/acb87b9319bc414db8d9ad5b0dbe1aa4/
    description: orchestration path component
    type: string
  orchestration_overwrite:
    default: ''
    description: orchestration specific apache overwrite (Base64)
    type: string
  orchestration_port:
    default: 8004
    description: orchestration frontend port
    type: int
  orchestration_securityrules:
    default: ''
    description: orchestration specific security rules
    type: string
  orchestration_ssl_cert:
    default: ''
    description: orchestration frontend SSL certificate (Base64)
    type: string
  orchestration_ssl_key:
    default: ''
    description: orchestration frontend SSL key (Base64)
    type: string
  securityrules:
    default: ''
    description: Global security rules (Base64)
    type: string
  ssl_webserver_ca:
    default: ''
    description: Global CA of all backend webservers (Base64)
    type: string
  volume_backend_proto:
    default: http
    description: 'volume backend protocol [http|https]'
    type: string
  volume_location:
    default: /v1/acb87b9319bc414db8d9ad5b0dbe1aa4/
    description: volume path component
    type: string
  volume_overwrite:
    default: ''
    description: volume specific apache overwrite (Base64)
    type: string
  volume_port:
    default: 8776
    description: volume frontend port
    type: int
  volume_securityrules:
    default: ''
    description: volume specific security rules
    type: string
  volume_ssl_cert:
    default: ''
    description: volume frontend SSL certificate (Base64)
    type: string
  volume_ssl_key:
    default: ''
    description: volume frontend SSL key (Base64)
    type: string
